language: java
jdk:
  - openjdk11
sudo: required 
dist: precise
before_install:
  - wget http://apache.mirror.iphh.net/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar xzvf apache-maven-3.6.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
  - mvn -v
after_success:
  - mvn clean test jacoco:report coveralls:report
